MASTER_GAMES = [
    {
        "title": "The Legend of Zelda: Breath of the Wild",
        "release_year": 2017,
        "platforms": "Switch, Wii U",
        "genres": "Action, Adventure",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "franchise": "The Legend of Zelda",
        "release_date": "2017-03-03",
        "platform_category": "Console",
        "description": "An open-world adventure across Hyrule with emergent exploration.",
        "popularity": 98,
        "screenshots": "plateau|shrine|field",
    },
    {
        "title": "God of War",
        "release_year": 2018,
        "platforms": "PlayStation 4, PC",
        "genres": "Action, Adventure",
        "developer": "Santa Monica Studio",
        "publisher": "Sony Interactive Entertainment",
        "franchise": "God of War",
        "release_date": "2018-04-20",
        "platform_category": "Console",
        "description": "A mythic father-son journey with cinematic combat.",
        "popularity": 95,
        "screenshots": "river|mountain|battle",
    },
    {
        "title": "Halo: Combat Evolved",
        "release_year": 2001,
        "platforms": "Xbox, PC",
        "genres": "Shooter",
        "developer": "Bungie",
        "publisher": "Microsoft Game Studios",
        "franchise": "Halo",
        "release_date": "2001-11-15",
        "platform_category": "Console",
        "description": "A sci-fi shooter that defined Xbox multiplayer.",
        "popularity": 82,
        "screenshots": "ringworld|covenant|warthog",
    },
    {
        "title": "The Witcher 3: Wild Hunt",
        "release_year": 2015,
        "platforms": "PC, PlayStation 4, Xbox One, Switch",
        "genres": "RPG",
        "developer": "CD Projekt Red",
        "publisher": "CD Projekt",
        "franchise": "The Witcher",
        "release_date": "2015-05-19",
        "platform_category": "Console",
        "description": "A sprawling RPG of monster hunting and political intrigue.",
        "popularity": 97,
        "screenshots": "novigrad|skellige|contract",
    },
    {
        "title": "Stardew Valley",
        "release_year": 2016,
        "platforms": "PC, Switch, PlayStation 4, Xbox One, Mobile",
        "genres": "Simulation, RPG",
        "developer": "ConcernedApe",
        "publisher": "ConcernedApe",
        "franchise": "Stardew Valley",
        "release_date": "2016-02-26",
        "platform_category": "PC",
        "description": "A cozy farming sim with deep town relationships.",
        "popularity": 90,
        "screenshots": "farm|mine|festival",
    },
    {
        "title": "Hades",
        "release_year": 2020,
        "platforms": "PC, Switch, PlayStation, Xbox",
        "genres": "Action, Roguelike",
        "developer": "Supergiant Games",
        "publisher": "Supergiant Games",
        "franchise": "",
        "release_date": "2020-09-17",
        "platform_category": "PC",
        "description": "A fast, stylish roguelike about escaping the underworld.",
        "popularity": 91,
        "screenshots": "styx|boss|upgrade",
    },
    {
        "title": "Minecraft",
        "release_year": 2011,
        "platforms": "PC, Console, Mobile",
        "genres": "Sandbox, Adventure",
        "developer": "Mojang",
        "publisher": "Mojang",
        "franchise": "Minecraft",
        "release_date": "2011-11-18",
        "platform_category": "PC",
        "description": "Build, explore, and survive in a limitless block world.",
        "popularity": 99,
        "screenshots": "overworld|nether|build",
    },
    {
        "title": "Celeste",
        "release_year": 2018,
        "platforms": "PC, Switch, PlayStation, Xbox",
        "genres": "Platformer",
        "developer": "Matt Makes Games",
        "publisher": "Matt Makes Games",
        "franchise": "",
        "release_date": "2018-01-25",
        "platform_category": "PC",
        "description": "A precision platformer about climbing a haunted mountain.",
        "popularity": 88,
        "screenshots": "summit|mirror|cave",
    },
    {
        "title": "Persona 5",
        "release_year": 2016,
        "platforms": "PlayStation 3, PlayStation 4",
        "genres": "RPG",
        "developer": "Atlus",
        "publisher": "Atlus",
        "franchise": "Persona",
        "release_date": "2016-09-15",
        "platform_category": "Console",
        "description": "A stylish JRPG about a team of phantom thieves.",
        "popularity": 89,
        "screenshots": "palace|battle|city",
    },
    {
        "title": "Monster Hunter: World",
        "release_year": 2018,
        "platforms": "PlayStation 4, Xbox One, PC",
        "genres": "Action, RPG",
        "developer": "Capcom",
        "publisher": "Capcom",
        "franchise": "Monster Hunter",
        "release_date": "2018-01-26",
        "platform_category": "Console",
        "description": "Hunt colossal creatures across living ecosystems.",
        "popularity": 86,
        "screenshots": "ancient_forest|hunt|workshop",
    },
    {
        "title": "Genshin Impact",
        "release_year": 2020,
        "platforms": "PC, PlayStation, Mobile",
        "genres": "Action, RPG",
        "developer": "miHoYo",
        "publisher": "miHoYo",
        "franchise": "",
        "release_date": "2020-09-28",
        "platform_category": "PC",
        "description": "An open-world action RPG with elemental team combat.",
        "popularity": 93,
        "screenshots": "mondstadt|combat|coast",
    },
    {
        "title": "Forza Horizon 4",
        "release_year": 2018,
        "platforms": "Xbox One, PC",
        "genres": "Racing",
        "developer": "Playground Games",
        "publisher": "Xbox Game Studios",
        "franchise": "Forza Horizon",
        "release_date": "2018-10-02",
        "platform_category": "Console",
        "description": "A dynamic open-world racing festival set in Britain.",
        "popularity": 84,
        "screenshots": "festival|storm|garage",
    },
    {
        "title": "The Last of Us Part II",
        "release_year": 2020,
        "platforms": "PlayStation 4",
        "genres": "Action, Adventure",
        "developer": "Naughty Dog",
        "publisher": "Sony Interactive Entertainment",
        "franchise": "The Last of Us",
        "release_date": "2020-06-19",
        "platform_category": "Console",
        "description": "A narrative-driven survival experience in a broken world.",
        "popularity": 87,
        "screenshots": "seattle|stealth|encounter",
    },
    {
        "title": "Animal Crossing: New Horizons",
        "release_year": 2020,
        "platforms": "Switch",
        "genres": "Simulation",
        "developer": "Nintendo",
        "publisher": "Nintendo",
        "franchise": "Animal Crossing",
        "release_date": "2020-03-20",
        "platform_category": "Console",
        "description": "Design your island and build a life with adorable neighbors.",
        "popularity": 92,
        "screenshots": "island|home|museum",
    },
    {
        "title": "Elden Ring",
        "release_year": 2022,
        "platforms": "PC, PlayStation, Xbox",
        "genres": "Action, RPG",
        "developer": "FromSoftware",
        "publisher": "Bandai Namco",
        "franchise": "",
        "release_date": "2022-02-25",
        "platform_category": "Console",
        "description": "A vast, mysterious world built for exploration and mastery.",
        "popularity": 96,
        "screenshots": "limgrave|castle|boss",
    },
]
